services:
  - type: web
    name: rutherglen-fire-brigade-app
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PIP_ONLY_BINARY
        value: ":all:"      # prefer wheels; avoids source builds
    disk:
      name: app-data
      mountPath: /opt/render/project/src/data
      sizeGB: 3
