services:
  - type: web
    name: rutherglen-fire-brigade-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: app-data
      mountPath: data
      sizeGB: 3
